version: '3.8'

services:
  survey:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - survey-db
  survey-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=survey
      - POSTGRES_PASSWORD=survey
      - POSTGRES_DB=survey_dev

volumes:
  postgres_data:
