# Generated by Django 2.2.16 on 2021-07-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_answers',
            new_name='choices',
        ),
    ]
