# Generated by Django 2.2.16 on 2021-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_answer_anonym_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='anonym_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
