# Generated by Django 2.2.16 on 2021-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20210712_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='entry_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='anonym_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
