# Generated by Django 2.2.16 on 2021-07-13 20:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210713_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('answer_type', 'text')},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('start_date', 'name')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('S', 'Единственный вариант ответа'), ('M', 'Множественный вариант ответа'), ('O', 'Свободный ответ')], default='O', max_length=1, verbose_name='тип ответа на вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата начала опроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='категория опроса'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='слаг категории опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=128, verbose_name='текст вопроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=64, verbose_name='имя опроса'),
        ),
    ]
