# Generated by Django 2.2.16 on 2021-07-15 12:08

import django.contrib.postgres.fields
from django.db import migrations, models
import survey.validators


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210714_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers_pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None, validators=[survey.validators.validate_answers_pool], verbose_name='варианты ответов'),
        ),
    ]
