# Generated by Django 2.2.16 on 2021-07-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20210719_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(help_text='sfsfs', primary_key=True, serialize=False, verbose_name='ID категории'),
        ),
    ]
