# Generated by Django 2.2.16 on 2021-07-27 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20210719_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='описание опроса'),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата конца опроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(help_text='ID категории', primary_key=True, serialize=False, verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(editable=False, verbose_name='дата начала опроса'),
        ),
    ]
